spring:
  application:
    name: addressAPI
  data:
    mongodb:
      uri: mongodb://mongodb:27017/logs  # Atualize de localhost para o nome do serviço 'mongodb'

server:
  servlet:
    context-path: /addressAPI
  port: 8080

feign:
  client:
    config:
      brasilApi:
        url: https://brasilapi.com.br/
      viacep:
        url: https://viacep.com.br

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      addressAPI:
        slidingWindowType: COUNT_BASED
        registerHealthIndicator: true
        failureRateThreshold: 100
        minimumNumberOfCalls: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 1

logging:
  level:
    root: INFO
    com.example: DEBUG

addressAPI:
  openapi:
    dev-url: http://localhost:8080/api-endereco

springdoc:
  api-docs:
    path: /api-endereco-api-docs
  swagger-ui:
    filter: true
    path: /api-endereco-documentation
    tryItOutEnabled: true
sonar:
  host:
    url: http://localhost:9000
  login: sqa_7cd6f9928f8de3a47db1048dd90c45b2d5b6283e
