management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      endereco:
        slidingWindowType: COUNT_BASED
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 3


logging:
  level:
    root: INFO  # Defina o nível de log global

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # Formato de log no console

  file:
    name: "logs/myapp.log"        # Caminho e nome do arquivo de log
