spring:
  application:
    name: api-endereco
  data:
    mongodb:
      uri:  mongodb://localhost:27017/api-endereco

server:
  servlet:
    context-path: /api-endereco
  port: 8080


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      endereco:
        slidingWindowType: COUNT_BASED
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 3


