spring:
  application:
    name: api-endereco
  data:
    mongodb:
      uri:  mongodb://localhost:27017/logs

server:
  servlet:
    context-path: /api-endereco
  port: 8080

feign:
  client:
    config:
      brasilApi:
        url: https://brasilapi.com.br/
      viacep:
        url: https://viacep.com.br


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      endereco:
        slidingWindowType: COUNT_BASED
        registerHealthIndicator: true
        failureRateThreshold: 100
        minimumNumberOfCalls: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 1

logging:
  level:
    root: INFO
    com.example: DEBUG



api-endereco:
  openapi:
    dev-url: http://localhost:8080/api-endereco
springdoc:
  api-docs:
    path: /api-endereco-api-docs
  swagger-ui:
    filter: true
    path: /api-endereco-documentation
    tryItOutEnabled: true