spring:
  profiles: test  # Define o perfil como 'test'

feign:
  client:
    config:
      viacep:
        url: https://viacep-mock-api.com  # Mock da API para testes
      brasilApi:
        url: https://brasilapi-mock.com  # Mock da outra API para testes

# Outras configurações de teste
server:
  port: 8081  # Porta personalizada para o ambiente de teste

logging:
  level:
    root: WARN
    org.springframework.web: ERROR
